- name: install npm (node package manager) with corresponding nodejs server itself
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - nodejs
    - npm


- name: fix openssl bug (https://stackoverflow.com/a/46476879)
  yum:
    name: openssl
    state: latest
